<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class NutritionsMenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        collect([
            [
                'menu_id'=> 1,
                'karbohidrat'=> 0,
                'karbohidrat_unit_id'=> 0,
                'protein'=> 0,
                'protein_unit_id'=> 0,
                'lemak'=> 0,
                'lemak_unit_id'=> 0,
                'serat'=> 0,
                'serat_unit_id'=> 0,
                'natrium'=> 0,
                'natrium_unit_id'=> 0,
                'kalori'=> 0,
                'kalori_unit_id'=> 0,
            ],
            [
                'menu_id'=> 2,
                'karbohidrat'=> 0,
                'karbohidrat_unit_id'=> 0,
                'protein'=> 0,
                'protein_unit_id'=> 0,
                'lemak'=> 0,
                'lemak_unit_id'=> 0,
                'serat'=> 0,
                'serat_unit_id'=> 0,
                'natrium'=> 0,
                'natrium_unit_id'=> 0,
                'kalori'=> 0,
                'kalori_unit_id'=> 0,
            ],
            [
                'menu_id'=> 3,
                'karbohidrat'=> 0,
                'karbohidrat_unit_id'=> 0,
                'protein'=> 0,
                'protein_unit_id'=> 0,
                'lemak'=> 0,
                'lemak_unit_id'=> 0,
                'serat'=> 0,
                'serat_unit_id'=> 0,
                'natrium'=> 0,
                'natrium_unit_id'=> 0,
                'kalori'=> 0,
                'kalori_unit_id'=> 0,
            ],
            [
                'menu_id'=> 4,
                'karbohidrat'=> 0,
                'karbohidrat_unit_id'=> 0,
                'protein'=> 0,
                'protein_unit_id'=> 0,
                'lemak'=> 0,
                'lemak_unit_id'=> 0,
                'serat'=> 0,
                'serat_unit_id'=> 0,
                'natrium'=> 0,
                'natrium_unit_id'=> 0,
                'kalori'=> 0,
                'kalori_unit_id'=> 0,
            ],
            [
                'menu_id'=> 5,
                'karbohidrat'=> 0,
                'karbohidrat_unit_id'=> 0,
                'protein'=> 0,
                'protein_unit_id'=> 0,
                'lemak'=> 0,
                'lemak_unit_id'=> 0,
                'serat'=> 0,
                'serat_unit_id'=> 0,
                'natrium'=> 0,
                'natrium_unit_id'=> 0,
                'kalori'=> 0,
                'kalori_unit_id'=> 0,
            ],
            [
                'menu_id'=> 6,
                'karbohidrat'=> 0,
                'karbohidrat_unit_id'=> 0,
                'protein'=> 0,
                'protein_unit_id'=> 0,
                'lemak'=> 0,
                'lemak_unit_id'=> 0,
                'serat'=> 0,
                'serat_unit_id'=> 0,
                'natrium'=> 0,
                'natrium_unit_id'=> 0,
                'kalori'=> 0,
                'kalori_unit_id'=> 0,
            ],
            [
                'menu_id'=> 7,
                'karbohidrat'=> 0,
                'karbohidrat_unit_id'=> 0,
                'protein'=> 0,
                'protein_unit_id'=> 0,
                'lemak'=> 0,
                'lemak_unit_id'=> 0,
                'serat'=> 0,
                'serat_unit_id'=> 0,
                'natrium'=> 0,
                'natrium_unit_id'=> 0,
                'kalori'=> 0,
                'kalori_unit_id'=> 0,
            ],
            [
                'menu_id'=> 8,
                'karbohidrat'=> 0,
                'karbohidrat_unit_id'=> 0,
                'protein'=> 0,
                'protein_unit_id'=> 0,
                'lemak'=> 0,
                'lemak_unit_id'=> 0,
                'serat'=> 0,
                'serat_unit_id'=> 0,
                'natrium'=> 0,
                'natrium_unit_id'=> 0,
                'kalori'=> 0,
                'kalori_unit_id'=> 0,
            ],
            [
                'menu_id'=> 9,
                'karbohidrat'=> 0,
                'karbohidrat_unit_id'=> 0,
                'protein'=> 0,
                'protein_unit_id'=> 0,
                'lemak'=> 0,
                'lemak_unit_id'=> 0,
                'serat'=> 0,
                'serat_unit_id'=> 0,
                'natrium'=> 0,
                'natrium_unit_id'=> 0,
                'kalori'=> 0,
                'kalori_unit_id'=> 0,
            ],
            [
                'menu_id'=> 10,
                'karbohidrat'=> 0,
                'karbohidrat_unit_id'=> 0,
                'protein'=> 0,
                'protein_unit_id'=> 0,
                'lemak'=> 0,
                'lemak_unit_id'=> 0,
                'serat'=> 0,
                'serat_unit_id'=> 0,
                'natrium'=> 0,
                'natrium_unit_id'=> 0,
                'kalori'=> 0,
                'kalori_unit_id'=> 0,
            ],
            [
                'menu_id'=> 11,
                'karbohidrat'=> 0,
                'karbohidrat_unit_id'=> 0,
                'protein'=> 0,
                'protein_unit_id'=> 0,
                'lemak'=> 0,
                'lemak_unit_id'=> 0,
                'serat'=> 0,
                'serat_unit_id'=> 0,
                'natrium'=> 0,
                'natrium_unit_id'=> 0,
                'kalori'=> 0,
                'kalori_unit_id'=> 0,
            ],
            [
                'menu_id'=> 12,
                'karbohidrat'=> 0,
                'karbohidrat_unit_id'=> 0,
                'protein'=> 0,
                'protein_unit_id'=> 0,
                'lemak'=> 0,
                'lemak_unit_id'=> 0,
                'serat'=> 0,
                'serat_unit_id'=> 0,
                'natrium'=> 0,
                'natrium_unit_id'=> 0,
                'kalori'=> 0,
                'kalori_unit_id'=> 0,
            ],
        ])->each(function ($nutritions_menu){
            DB::table('nutritions_menus')->insert($nutritions_menu);
        });
    }
}
